version: '3.3'

services:
   web:
     depends_on:
       - db
     image: rossedlin/apache-php:7.2
     ports:
       - "80:80"
     env_file:
       - .env
     volumes:
       - ./:/var/www

   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - db:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: Passw0rd
       MYSQL_DATABASE: api
       MYSQL_USER: api
       MYSQL_PASSWORD: Passw0rd

volumes:
    db: